server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RatingMicroservice
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka

