server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserMicroservice
    username: postgres
    password: postgres


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: USER-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka